### PR TITLE
update etcd client and go mod

### PR DESCRIPTION
**Pull request by ti**
1. upgrade etcd client to v3 go.etcd.io/etcd/v3
2. upgrade Gopkg to go mod

This library is really great, but after `etcd` upgrade to `etcd/v3`, the `go-etcd-lock` can not use.  so i upgrade it

### CODE REVIEW

**Comment by Soulou** [comment]
Thanks a lot for your contribution!

For go mod it's great, but about the change in the import, can you give me the source where you saw we should use

`go.etcd.io/etcd/v3/clientv3` instead of `go.etcd.io/etcd/clientv3`?

In the documentation examples: https://godoc.org/go.etcd.io/etcd/clientv3 This import path is never used.

Thanks a lot

**Comment by ti** [comment]
@Soulou the etcd client master branch source code is already changed 

https://github.com/etcd-io/etcd/blob/master/clientv3/client.go

the client version is `go.etcd.io/etcd/v3 v3.3.0-rc.0.0.20200518175753-732df43cf85b`

**Comment by ti** [comment]
@Soulou Do you have any other concerns?

**Comment by Soulou** [comment]
@ti the project is not using `go.etcd.io/etcd/v3/client` but `go.etcd.io/etcd/clientv3` 

https://github.com/etcd-io/etcd/tree/master/clientv3 and in that place the import path is not really precised, so by default I prefer not having the version in the URL and use solely the features from `go mod` to handle the version.

It seems to me `go.etcd.io/etcd/v3/client` is the 3rd version of the client for the API v2 of ETCD

**Comment by Soulou** [comment]
Ok my bad, after looking a bit more in details, it's etcd which changed their way to do in this commit: https://github.com/etcd-io/etcd/commit/96cce208c2cb9e70ac3573b3f76eed7c84d262d1

So indeed we need to use /v3, apologies for me doubting

**Comment by Soulou** [comment]
Bumped to v5.0.0 e87c7b1

**Comment by ti** [comment]
thanks。👍👍

**Pull request merged**
